services:
  #web:
    #container_name: web-app
    #build: .
    #ports:
    #  - "4000:4000"
    #volumes:
    #  - .:/app
    #environment:
    #  - FLASK_ENV=development
    
  db:
    image: postgres:16-alpine
    container_name: banco-de-dados-postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: nota-fiscal-python
    ports:
      - "4005:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nota-fiscal-python"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

    restart: always

  pgadmin:
    container_name: interface_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
    - "4006:80"
    depends_on:
      - db
volumes:
  postgres_data:
  
      