name: Imagem Docker NFS-e em Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

   deploy:
    runs-on: ubuntu-24.04 
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login do docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

